# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 11:38
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Hunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('circumstances', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Hunter',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.IntegerField(choices=[(0, 'Hunter'), (1, 'Officer'), (2, 'Manager')], default=0)),
                ('age', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=100)),
                ('available', models.BooleanField(default=True)),
                ('Stamina', models.IntegerField(default=6)),
                ('Strength', models.IntegerField(default=39)),
                ('Agility', models.IntegerField(default=78)),
                ('Intellect', models.IntegerField(default=57)),
                ('Speed', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Hunter',
                'verbose_name_plural': 'Hunters',
                'permissions': (('see_watches', 'See watches'),),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HunterAbilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.IntegerField(default=0)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Abilities')),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Hunter')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Mammoth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=100)),
                ('hunted', models.BooleanField(default=False)),
                ('behavior', models.CharField(max_length=128)),
                ('character', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Mammoth',
                'verbose_name_plural': 'Mammoths',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_mammoths', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('hunters', models.ManyToManyField(to='app.Hunter')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Location')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='from_watch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Watch'),
        ),
        migrations.AddField(
            model_name='message',
            name='mammoths',
            field=models.ManyToManyField(to='app.Mammoth'),
        ),
        migrations.AddField(
            model_name='mammoth',
            name='killedIn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pit'),
        ),
        migrations.AddField(
            model_name='hunter',
            name='killedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Mammoth'),
        ),
        migrations.AddField(
            model_name='hunter',
            name='killedIn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Hunt'),
        ),
        migrations.AddField(
            model_name='hunt',
            name='hunters',
            field=models.ManyToManyField(to='app.Hunter'),
        ),
        migrations.AddField(
            model_name='hunt',
            name='pits',
            field=models.ManyToManyField(to='app.Pit'),
        ),
        migrations.AddField(
            model_name='hunt',
            name='started_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Message'),
        ),
        migrations.AlterUniqueTogether(
            name='hunterabilities',
            unique_together=set([('hunter', 'ability')]),
        ),
    ]
