# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 20:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hunter',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=64)),
                ('role', models.IntegerField(choices=[(0, 'Hunter'), (1, 'Officer'), (2, 'Manager')], default=0)),
                ('age', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=100)),
                ('available', models.IntegerField(default=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Mammoth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('health', models.IntegerField(default=100)),
                ('hunted', models.BooleanField(default=False)),
                ('behavior', models.CharField(max_length=128)),
                ('character', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.BooleanField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Location')),
            ],
        ),
        migrations.AddField(
            model_name='mammoth',
            name='killedIn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pit'),
        ),
        migrations.AddField(
            model_name='hunter',
            name='killedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Mammoth'),
        ),
    ]
