# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunter',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='killedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Mammoth'),
        ),
        migrations.AlterField(
            model_name='mammoth',
            name='killedIn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pit'),
        ),
    ]
