# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hunterabilities',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='hunterabilities',
            name='ability',
        ),
        migrations.RemoveField(
            model_name='hunterabilities',
            name='hunter',
        ),
        migrations.AlterModelOptions(
            name='watch',
            options={'verbose_name': 'Watch', 'verbose_name_plural': 'Watches'},
        ),
        migrations.DeleteModel(
            name='Abilities',
        ),
        migrations.DeleteModel(
            name='HunterAbilities',
        ),
    ]
