# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171119_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hunter',
            name='name',
        ),
    ]
