# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171129_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mammoth',
            name='character',
        ),
        migrations.AlterField(
            model_name='hunter',
            name='Agility',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='Intellect',
            field=models.IntegerField(default=78),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='Speed',
            field=models.IntegerField(default=27),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='Stamina',
            field=models.IntegerField(default=78),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='Strength',
            field=models.IntegerField(default=29),
        ),
    ]
