# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default=' ', max_length=128),
        ),
    ]
