# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_hunter_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hunter',
            options={'verbose_name': 'Hunter', 'verbose_name_plural': 'Hunters'},
        ),
    ]
