# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171119_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Hunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=True)),
                ('circumstances', models.CharField(max_length=128)),
                ('hunters', models.ManyToManyField(to='app.Hunter')),
            ],
        ),
        migrations.CreateModel(
            name='HunterAbilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.IntegerField(default=0)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Abilities')),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Hunter')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_mammoths', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hunters', models.ManyToManyField(to='app.Hunter')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Location')),
            ],
        ),
        migrations.AlterModelOptions(
            name='mammoth',
            options={'verbose_name': 'Mammoth', 'verbose_name_plural': 'Mammoths'},
        ),
        migrations.AlterField(
            model_name='pit',
            name='taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='from_watch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Watch'),
        ),
        migrations.AddField(
            model_name='message',
            name='mammoths',
            field=models.ManyToManyField(to='app.Mammoth'),
        ),
        migrations.AddField(
            model_name='hunt',
            name='pits',
            field=models.ManyToManyField(to='app.Pit'),
        ),
        migrations.AddField(
            model_name='hunt',
            name='started_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Message'),
        ),
        migrations.AddField(
            model_name='hunter',
            name='killedIn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Hunt'),
        ),
        migrations.AlterUniqueTogether(
            name='hunterabilities',
            unique_together=set([('hunter', 'ability')]),
        ),
    ]
