# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171127_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hunter',
            options={'permissions': (('see_watches', 'See watches'),), 'verbose_name': 'Hunter', 'verbose_name_plural': 'Hunters'},
        ),
    ]
