# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171129_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hunt',
            name='started_by',
        ),
        migrations.AddField(
            model_name='hunt',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Mammoth'),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='Agility',
            field=models.IntegerField(default=44),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='Intellect',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='Speed',
            field=models.IntegerField(default=68),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='Stamina',
            field=models.IntegerField(default=69),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='Strength',
            field=models.IntegerField(default=76),
        ),
    ]
