# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171130_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunter',
            name='Agility',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='Intellect',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='Speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='Stamina',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='Strength',
            field=models.IntegerField(default=0),
        ),
    ]
