# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20171130_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunt',
            name='pit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pit'),
        ),
    ]
