# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171129_0802'),
        ('app', '0010_auto_20171130_1051'),
    ]

    operations = [
    ]
