# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20171201_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mammoth',
            name='hunted',
        ),
        migrations.AlterField(
            model_name='mammoth',
            name='killedIn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Hunt'),
        ),
    ]
